//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAHUL_CRUD_NEW.Rahul
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu_Table
    {
        public int RollNo { get; set; }
        public string Name { get; set; }
        public int Class { get; set; }
        public int P_Marks { get; set; }
        public int T_Marks { get; set; }
        public string Add { get; set; }
        public string Mobile { get; set; }
    }
}
